### ISSUE TITLE
on focus out signal fix

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#10]
sorry bu I can't do it my self 

can you please change on the float_touchpad.glade and others 
on Gtk.Window the "Window Type" property from "popup or emergent" to top "Top Level" and see if the signal fires?

Thanks

**Comment by KurtJacobson** [comment]
I was hopping you would see that comment! 
I can get the signal to fire if I set the window to top-level, and then "hide on focus out" works exactly how I want it to, the problem is that then the DRO entry does not get focus, I guess since the window gets the focus instead. What I need is a signal that fires when the "Z-order" (don't know what the GTK term is) changes.
I have tried every possible combination of toplevel, popup, modal etc. that is available in glade, and none of them seem to provide what I need.

I am going to create a new branch with the window set to toplevel for you to look at. Thanks for your help, it is greatly appreciated!!

**Comment by KurtJacobson** [comment]
branch popup, changed only int numpad. try on spindle speed or tool num entry

**Comment by TurBoss** [comment]
I added 
```
        self.window.set_keep_above(True) 
```
To line 49 on Touchpad and it goes to front but the signal only works once you manually close the window once

**Comment by KurtJacobson** [comment]
That does not change anything for me, I guess it might depend on the window manager being used.
The main problem is that the text in the DRO does not get highlighted like it should, so when I type in text there is no cursor showing and any existing text does not get overwritten. Here is a screen shot of what I am looking for, but this is with the window as a popup so it does not fire the focus out signal.

![screenshot_5](https://cloud.githubusercontent.com/assets/19997275/25319311/737e6b86-286a-11e7-944d-155b18eb40d5.png)

**Comment by TurBoss** [comment]
ok the keypad never has focus so can't lost it :D

it should give focus to keypad on show and manipulate the text_input with python

**Comment by TurBoss** [comment]
https://www.youtube.com/watch?v=tDuja3V1Imk
https://youtu.be/ER9-m85z8ZE

**Comment by KurtJacobson** [comment]
Thanks for the videos! 
What bothers me is not having the cursor show in the DRO when entering text, but that is not really a big deal. I like the green highlight in the DRO. It is almost as good as the cursor, did you add that or is that just your window manager? If it is just your window manager I think I will add a highlight like that.

**Comment by TurBoss** [comment]
is done via python with
widget.modify_base(gtk.STATE_NORMAL, gtk.gdk.color_parse("green"))

**Comment by KurtJacobson** [comment]
I though so! Thank you!!

**Comment by TurBoss** [comment]
I'm ready for a pull request, or are you working on it?

I manually modified the glade file because glade3.8.5 doesn't compile on ubuntu 16.10 (will fix soon or later)

**Comment by KurtJacobson** [comment]
Go ahead and do a pull request to popup and I'll merge that later.

**Comment by KurtJacobson** [comment]
Right now I am working on making a new filechooser that is more thouch friendly and will allow renaming of files and the like.

**Comment by KurtJacobson** [comment]
Since the GTK entry was not getting the focus the numpad did not work on the treeviews (tooledit and filechooser). What I ended up doing is adding a `widget.connect('focus-out-event', self.on_entry_loses_focus)` to the Touchpad show method and hiding the popup when that was fired. I think that is the best solution for now. It is in master.
Let me know what you think.
Thanks!

**Comment by TurBoss** [comment]
Ok so now closes the touchpad when the text entry looses the focus, good idea
I made a little change, I'm making a pull request

```
widget.connect(...
```
is equal to
```
self.dro.connect(...
```
as the widget is stored in "self.dro"

**Comment by TurBoss** [comment]
The branch "popup" can be deleted

**Comment by TurBoss** [comment]
bu bu but it only closes the touchpad when you click on something that can get focus...
is this happening to you ?

**Comment by KurtJacobson** [comment]
Sorry, I've been busy all day making model airplanes for some aerospace engineers. Done at last.

![20170425_185313](https://cloud.githubusercontent.com/assets/19997275/25414262/998c0a50-29fe-11e7-8d67-0ea942cb5c38.jpg)

**Comment by KurtJacobson** [comment]
Your right, that is a problem. But at least it works on the treeviews and solves the biggest nuisance of the numpad staying up even when the DRO has lost focus. 

I wonder if instead of trying to catch a focus change it would be possible to determine if a button press occurs outside of the popup, and exit out then. What do you think? 

Again, thank you for all your help!
